Updated cucumber libraries & aligned the sbt version with jenkins con…
nationalarchives/tdr-e2e-tests pull request #159
Opened 2022-01-30 23:45 UTC by jaymdavey

…figuration.

2022-01-31 08:54 UTC, TomJKing requested changes
Just one minor comment on the code.

In addition can you ensure you update the README instructions with changes related to the upgrade.

Specifically:

- At line 64: Currently reads: `Glue: "classpath:steps/"`, should be `Glue: "classpath:steps"`
- New instructions after line 70: `Program agruments: --plugin
org.jetbrains.plugins.cucumber.java.run.CucumberJvm4SMFormatter`

2022-01-31 08:54 UTC, TomJKing commented on project/build.properties
> +sbt.version = 1.4.1
Add single line blank line break to end of file.

2022-02-01 13:10 UTC, jaymdavey commented
> Just one minor comment on the code.
> 
> In addition can you ensure you update the README instructions with changes related to the upgrade.
> 
> Specifically:
> 
> * At line 64: Currently reads: `Glue: "classpath:steps/"`, should be `Glue: "classpath:steps"`

With library updates, api signatures have changed & it is now sufficient to just specify the package name. So it now reads just "`Glue: "steps"`

> * New instructions after line 70: `Program agruments: --plugin 
> org.jetbrains.plugins.cucumber.java.run.CucumberJvm4SMFormatter`

I've added usage of `Program arguments: --plugin
 org.jetbrains.plugins.cucumber.java.run.CucumberJvm5SMFormatter as it is working fine. I've added a line to use CucumberJvm4SMFormatter in case of exceptions.

2022-02-01 13:10 UTC, jaymdavey commented on project/build.properties
> +sbt.version = 1.4.1
I've added this.

2022-02-01 13:22 UTC, TomJKing approved these changes

2022-02-01 13:40 UTC, merged