Add test for checksum progress bar
nationalarchives/tdr-e2e-tests pull request #51
Opened 2020-09-28 16:20 UTC by techncl

2020-09-30 10:11 UTC, Lholbourn commented on src/test/scala/steps/Steps.scala
> +    createdFiles.drop(4).foreach(id => client.createClientsideMetadata(userCredentials, id, "checksumValue")) //checksumValue will be replaced with actual checksum soon
If you're dropping all 4 of 4 files, then I think this line won't be doing anything. Drop returns all elements except the first _N_ ones.

2020-09-30 10:13 UTC, Lholbourn commented on src/test/scala/steps/Steps.scala
> +      val id: String = targetIdName.replaceAll(" ", "-")
It's much easier to read this now that it's a bit more simplified! :+1:

2020-09-30 10:13 UTC, Lholbourn commented on src/test/scala/helpers/graphql/GraphqlUtility.scala
> +  def createClientsideMetadata(userCredentials: UserCredentials, fileId: UUID, checksumValue: String): Unit = {
Do we need to be doing this since the progress bar only checks the back end metadata progress?

2020-09-30 10:14 UTC, Lholbourn commented on src/test/resources/features/FileChecks.feature
> +  Scenario: A user will see checksum progress bar on the file checks page
Looks good! :smile:

2020-09-30 10:15 UTC, Lholbourn requested changes
Looks good, I had a few questions that I've left comments for :smile:

2020-09-30 10:31 UTC, techncl commented on src/test/scala/steps/Steps.scala
> +    createdFiles.drop(4).foreach(id => client.createClientsideMetadata(userCredentials, id, "checksumValue")) //checksumValue will be replaced with actual checksum soon
Thank you for reviewing! :facepalm: That was meant to be a 3 like the backend check one. Good spot! But now I realise that it actually doesn't need to drop any files (on the client-side); it should add the checksum to all files from the client and only do the backend checks on 25% because that it is closer to real life (even though it would take slightly longer to add 4 files to the database). I'll change it now.

2020-09-30 10:31 UTC, techncl commented on src/test/scala/steps/Steps.scala
> +      val id: String = targetIdName.replaceAll(" ", "-")
Thanks :+1:

2020-09-30 10:46 UTC, techncl commented on src/test/scala/helpers/graphql/GraphqlUtility.scala
> +  def createClientsideMetadata(userCredentials: UserCredentials, fileId: UUID, checksumValue: String): Unit = {
This was something that Tom asked me to add. It's not 100% necessary for this test, but I guess it's more realistic as the file will have the full amount of metadata (which might come in handy for future tests). I could maybe move it higher in the "an existing upload" step, so that it's a little clearer?

2020-09-30 10:46 UTC, techncl commented on src/test/resources/features/FileChecks.feature
> +  Scenario: A user will see checksum progress bar on the file checks page
Thanks! :+1:

2020-09-30 12:56 UTC, Lholbourn commented on src/test/scala/helpers/graphql/GraphqlUtility.scala
> +  def createClientsideMetadata(userCredentials: UserCredentials, fileId: UUID, checksumValue: String): Unit = {
Will it be useful for all 3 of the metadata or just the checksum metadata? I think if it's needed in the future for all 3 types of metadata it's probably smart to put it a bit higher yeah :+1:

2020-09-30 12:57 UTC, Lholbourn commented on src/test/scala/steps/Steps.scala
> +    createdFiles.drop(4).foreach(id => client.createClientsideMetadata(userCredentials, id, "checksumValue")) //checksumValue will be replaced with actual checksum soon
Ah cool, that makes more sense!

2020-09-30 13:28 UTC, techncl commented on src/test/scala/helpers/graphql/GraphqlUtility.scala
> +  def createClientsideMetadata(userCredentials: UserCredentials, fileId: UUID, checksumValue: String): Unit = {
I'm not 100% sure (the "datetime" field is a part of the AVMetadata and FFIDMetadata, but not sure if we're keeping that field), but I was thinking since in production, the metadata will get added before the backend checks start, it might make sense to add it right after the file gets added so that it kind of mimics the upload process especially since this method also tests the part where the user gets a user token from Keycloak in order to upload their files.

2020-10-01 08:48 UTC, Lholbourn commented on src/test/scala/helpers/graphql/GraphqlUtility.scala
> +  def createClientsideMetadata(userCredentials: UserCredentials, fileId: UUID, checksumValue: String): Unit = {
Yeah, I think getting it as close to realistic user/back end behaviour as possible is a good idea! :+1:

2020-10-01 10:17 UTC, Lholbourn approved these changes
Looks good! :rocket:

2020-10-01 10:18 UTC, merged