Tdr 414 ffid progress
nationalarchives/tdr-e2e-tests pull request #52
Opened 2020-10-05 13:58 UTC by Lholbourn

These changes add a test scenario for the FFDIMetadata progress bar, with a new GraphqlUtility function to add FFIDMetadata to the appropriate table and, removes the manual upload scenario from the fileChecks scenarios file.

I have added a step to simulate the user waiting for backend checks to complete, to allow us to check that the redirect only happens when all checks are complete and to let us remove the 'manual' test user upload. This functionality is a little clumsy at the moment and definitely needs refactoring, but I was unsure of which direction to go with it.

2020-10-06 11:39 UTC, techncl requested changes

2020-10-06 11:39 UTC, techncl commented on src/test/scala/steps/Steps.scala
>      createdFiles.drop(1).foreach(id => client.createAVMetadata(id))
Now that you've added the "the user waits for the checks to complete" step (below), I think it makes more sense to add these 3 backend checks to that step. The reason why is that in production, at the point of the "existing upload" step, only the creation of files and the adding of client metadata would be done. Another thing that prompted this thought was the fact that you are doing the backend stuff in the step below again. So this would reduce code and it will give us a clear distinction between what the frontend and backend.

Then in the features file, the step "the user waits for the checks to complete" can be added to each of the progress bar scenarios (right before the "And the x progress bar should be visible").

2020-10-06 11:39 UTC, techncl commented on src/test/scala/steps/Steps.scala
> +//  checksumValue will be replaced with actual checksum soon
I think this comment should be above the code.

2020-10-09 08:15 UTC, suzannehamilton commented on src/test/scala/steps/Steps.scala
>      createdFiles.drop(1).foreach(id => client.createAVMetadata(id))
Looking back at the feature file, it's not currently clear where the progress percentages come from.

What about splitting the steps up so it's more like this?

```
    ...
    And an existing upload of 4 files
    And 3 of antivirus scans have finished
    When the user is logged in on the records page
    Then the user will be on a page with the title "Checking your records"
    And the checksum progress bar should be visible
    And the checksum progress bar should have 75% progress
```

Then you can work out from the feature that the 75% is related to the 3 scans and the 4 files, and it's clear which step sends the metadata to the API?

2020-10-09 09:51 UTC, techncl commented on src/test/scala/steps/Steps.scala
>      createdFiles.drop(1).foreach(id => client.createAVMetadata(id))
So would that mean in the steps file, it will look something like this  
```
And("^an existing upload of 4 files") {
    val client = GraphqlUtility(userCredentials)
    createdFiles = client.createFiles(consignmentId, 4)
//  checksumValue will be replaced with actual checksum soon
    createdFiles.foreach(id => client.createClientsideMetadata(userCredentials, id, "checksumValue"))
  }

  And("^3 of the (.*) scans have finished") {
    scan: String =>
  //  75% progress has been chosen for the progress bars as this is more realistic to test than using 100% or 0%.
      createdFiles.drop(1).foreach{ id =>
      scan match {
        case "antivirus" => client.createAVMetadata(id)
        case "checksum" => client.createBackendChecksumMetadata(id)
        case "file format" => client.createFFIDMetadata(id)
    }
  }
```
So in the final scenario in the file checks file, the second-last step, would be replaced by these?

 ```
And 3 of antivirus scans have finished
And 3 of checksum scans have finished
And 3 of file format scans have finished
```

In other words, would the final scenario have to go through the 3 scan steps again, or is it enough to add just 1 file (the dropped one) like in Loki's current iteration?

2020-10-14 17:34 UTC, techncl requested changes
Forgot to add my review :man_facepalming: . Looks good! Just a few comments.

2020-10-14 17:34 UTC, techncl commented on src/test/scala/steps/Steps.scala
> +      if (metadataType.contains("antivirus")) {
1. I think that `createdFiles.slice(0, filesProcessed)` could be moved to the top of the anonymous function (right above the `if` statement) and saved to a variable since it's the same set of files.

b. `createdFiles.drop(filesProcessed)` could also be added to a function as well just to reduce duplication

2. I think that maybe a match expression might look a bit cleaner here rather than an `if`

3. I also think that `filesProcessed` should be renamed to `filesToProcess`

2020-10-14 17:37 UTC, techncl requested changes

2020-10-14 17:37 UTC, techncl commented on src/test/scala/steps/Steps.scala
>      val createdFiles: List[UUID] = client.createFiles(consignmentId, 1)
This step is redundant now, right?

2020-10-15 09:42 UTC, Lholbourn commented on src/test/scala/steps/Steps.scala
>      val createdFiles: List[UUID] = client.createFiles(consignmentId, 1)
I don't think so since it's used in the test Sam add: `User is redirected to the results page if the checks are complete and they visit the record checks page`

2020-10-15 10:17 UTC, techncl commented on src/test/scala/steps/Steps.scala
>      val createdFiles: List[UUID] = client.createFiles(consignmentId, 1)
Ah, ok, but it does the same thing as the new steps you've added, i.e. creates the files, client metadata, and adds the backend metadata. But I guess it's more succinct than adding all of those steps again.

2020-10-15 11:05 UTC, techncl commented
> Ah, I think that's the GitHub UI since the old code from line 272 wrapped over. If you look on the `unified` view there's no extra line

Oh, I see. Cool, everything looks good to me!

2020-10-15 11:05 UTC, techncl approved these changes

2020-10-15 12:46 UTC, merged